version: '3.4'

services:
    postgresql:
        image: postgres:15
        container_name: postgresql
        ports:
          - 5432:5432
        environment:
          - POSTGRES_PASSWORD=admin
          - POSTGRES_USER=admin
          - POSTGRES_DB=admin
        networks:
          - network
        volumes:
        - pgdata:/var/lib/postgresql/data
    
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
          - PGADMIN_DEFAULT_EMAIL=exp3ct@yandex.ru
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
          - 5050:80
        networks:
          - network
        volumes:
        - pgadmindata:/var/lib/pgadmin    

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - 8080:15672
        networks:
            - network
    applicationreceiverservice:
        image: ${DOCKER_REGISTRY-}applicationreceiverservice
        build:
          context: .
          dockerfile: ApplicationReceiverService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOTNET_USE_POLLING_FILE_WATCHER=1
        networks:
          - network


    usercreationservice:
        image: ${DOCKER_REGISTRY-}usercreationservice
        build:
          context: .
          dockerfile: UserCreationService/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOTNET_USE_POLLING_FILE_WATCHER=1
        networks:
          - network


networks:
  network:
    driver: bridge

volumes:
  pgdata:
  pgadmindata:
    
